### ISSUE TITLE
NullPointer, exclusively on Android 6.0

### ISSUE THREAD

**Issue by Yonjuni** [SecUSo/privacy-friendly-netmonitor#38]
`
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleCreateService(ActivityThread.java:2897)
  at android.app.ActivityThread.access$1900(ActivityThread.java:165)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1459)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:150)
  at android.app.ActivityThread.main(ActivityThread.java:5621)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
Caused by: java.lang.NullPointerException: 
  at org.secuso.privacyfriendlynetmonitor.ConnectionAnalysis.PassiveService.getStringNew(PassiveService.java:100)
  at org.secuso.privacyfriendlynetmonitor.ConnectionAnalysis.PassiveService.getVersionString(PassiveService.java:92)
  at org.secuso.privacyfriendlynetmonitor.ConnectionAnalysis.PassiveService.<init>(PassiveService.java:87)
  at java.lang.Class.newInstance(Native Method:0)
  at android.app.ActivityThread.handleCreateService(ActivityThread.java:2894)
`

**Comment by 3lR0m4c** [comment]
Tested on Android 6.0.
