### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by rosc2112** [SecUSo/privacy-friendly-netmonitor#57]
Latest version on f-droid won't even start up. Running android 4.4.4 on at zte n817. Not much I can do for debug as virgin mobile has this thing locked down tight so I can't access logs. Not sure adb will do the job either, my data cable needs replacing.

**Comment by gdgsdg123** [comment]
Reproduced? on a different device of Android 4.4.4 (API 19):
```
Process: org.secuso.privacyfriendlynetmonitor
Flags: 0xe8be44
Package: org.secuso.privacyfriendlynetmonitor v8 (2.0)
Build: Xiaomi/full_lte26007/lte26007:4.4.4/KTU84Q/6.1.28:user/release-keys

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.secuso.privacyfriendlynetmonitor/org.secuso.privacyfriendlynetmonitor.Activities.MainActivity}: android.view.InflateException: Binary XML file line #23: Error inflating class android.support.design.widget.FloatingActionButton
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2258)
	at android.app.ActivityThread.access$800(ActivityThread.java:147)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5135)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class android.support.design.widget.FloatingActionButton
	at android.view.LayoutInflater.createView(LayoutInflater.java:623)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:842)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:748)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
	at org.secuso.privacyfriendlynetmonitor.Activities.MainActivity.activateMainView(MainActivity.java:169)
	at org.secuso.privacyfriendlynetmonitor.Activities.MainActivity.onCreate(MainActivity.java:126)
	at android.app.Activity.performCreate(Activity.java:5358)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2163)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:597)
	... 25 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_play_arrow.xml from drawable resource ID #0x7f08006b
	at android.content.res.Resources.loadDrawable(Resources.java:2179)
	at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:393)
	at android.content.res.Resources.loadDrawable(Resources.java:2102)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
	at android.widget.ImageView.<init>(ImageView.java:129)
	at android.widget.ImageButton.<init>(ImageButton.java:87)
	at android.support.design.widget.VisibilityAwareImageButton.<init>(VisibilityAwareImageButton.java:36)
	at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:155)
	at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:151)
	... 28 more
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:935)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:879)
	at android.content.res.Resources.createFromXml(Resources.java:2555)
	at android.content.res.Resources.loadDrawable(Resources.java:2175)
	... 36 more

```
Build from: https://github.com/SecUSo/privacy-friendly-netmonitor/releases/download/v2.0/PF-net-monitor_v2.0.apk

Identical extrinsic symptoms as #68.

**Comment by sleep-yearning** [comment]
Can you check if this is still a problem with release 2.1? There were some fixes for older devices inside.

**Comment by gdgsdg123** [comment]
> Quote [sleep-yearning](https://github.com/SecUSo/privacy-friendly-netmonitor/issues/57#issuecomment-698311949):
>
>> Quote [gdgsdg123](https://github.com/SecUSo/privacy-friendly-netmonitor/issues/57#issuecomment-565794530):
>>
>> ...
>>
>> Identical extrinsic symptoms as #68.
>
> Can you check if this is still a problem with release 2.1? There were some fixes for older devices inside.
>
> Reading your stacktrace I think that one should be solved.

> Quote [pdgilbert](https://github.com/SecUSo/privacy-friendly-netmonitor/issues/68#issuecomment-702355429):
>
> Yes, 2.1 on Android 4.2.1 with my Google Nexus phone seems to be working fine now. Thanks again for this great app.

I believe so, then.

**Comment by sleep-yearning** [comment]
Okay great, closing this.
